# -*- coding: utf-8 -*-
"""PhanTich_TienXuly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zYO787zjA-ADWDE6LKK76xwJRXWkQO2g

# Phân tích dữ liệu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('diabetes.csv')

print("--- Thông tin tổng quan ---")
print(df.info())
print("\n--- Thống kê chi tiết ---")
print(df.describe())

#TRỰC QUAN

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (15, 10)

#histo
df.hist(bins=20, color='skyblue', edgecolor='black', layout=(3, 3))
plt.suptitle("Biểu đồ Histogram của các đặc trưng", fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

#Ktra outliers
fig, axes = plt.subplots(nrows=3, ncols=3, figsize=(18, 15))
fig.subplots_adjust(hspace=0.4, wspace=0.3)
fig.suptitle('Biểu đồ Box Plot cho từng đặc trưng', fontsize=20)

for i, col in enumerate(df):
    row = i // 3
    axis = i % 3
    sns.boxplot(x=df[col], ax=axes[row, axis], color='green', fliersize=5)
    axes[row, axis].set_title(f'Phân phối của {col}', fontsize=14)
    axes[row, axis].set_xlabel('')

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

cols_to_plot = ['Pregnancies', 'Glucose', 'BloodPressure', 'BMI', 'Age', 'Outcome']

sns.set(style="ticks")
pair_plot = sns.pairplot(df[cols_to_plot], hue="Outcome", corner=True, palette="husl", diag_kind="kde")
pair_plot.fig.suptitle("Ma trận Scatter Plot giữa các cặp đặc trưng quan trọng", y=1.02, fontsize=16)
plt.show()

# # TƯƠNG QUAN dùng heat
# plt.figure(figsize=(12, 10))
# correlation_matrix = df.corr()
# sns.heatmap(correlation_matrix, annot=True, cmap='RdBu_r', fmt='.2f', linewidths=0.5)
# plt.title("Ma trận tương quan Heatmap", fontsize=16)
# plt.show()

"""# Tiền xử lý dữ liệu"""

import numpy as np
import pandas as pd

#preg (số lần mang thai) co thể có 0 vì có nam, hoặc nữ chưa sinh
cols_to_fix = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

#những cột khác = 0 --> không hợp lý --> điền nan
df[cols_to_fix] = df[cols_to_fix].replace(0, np.nan)

## điền mean
for col in cols_to_fix:
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)
    print(f"Đã thay thế các giá trị 0 ở cột '{col}' bằng trung bình: {mean_value:.2f}")

#check lại
print("\nSố lượng giá trị 0 sau khi xử lý:")
print((df[cols_to_fix] == 0).sum())

df_cleaned = df.copy()

cols_ = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction']

for col in cols_:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_cleaned[col] = df_cleaned[col].clip(lower=lower_bound, upper=upper_bound)

print("Đã xử lý xong ngoại lai.")

fig, axes = plt.subplots(nrows=2, ncols=4, figsize=(18, 10))
fig.suptitle('Box Plot SAU KHI xử lý ngoại lai', fontsize=20)
cols_ = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
for i, col in enumerate(cols_):
    row, axis = i // 4, i % 4
    sns.boxplot(x=df_cleaned[col], ax=axes[row, axis], color='lightgreen')
    axes[row, axis].set_title(f'{col} (Cleaned)')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

print(df_cleaned.info())

from sklearn.preprocessing import StandardScaler

X = df_cleaned.drop('Outcome', axis=1) # bỏ outcome
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df.head()

df_cleaned.to_csv('diabetes_cleaned.csv', index=False)
print("Đã lưu file: diabetes_cleaned.csv")

# lưu dữ liệu đã chuẩn hóa (X_scaled)
X_scaled_df.to_csv('diabetes_processed.csv', index=False)
print("Đã lưu file: diabetes_processed.csv")